name: Example Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
  #release:
    #types: [published]
  workflow_dispatch:
    branch:
      description: Branch

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Build
        run: |
          echo "linux-x86_64" > release
      - uses: actions/upload-artifact@v4
        with:
          name: release-linux-x86_64
          path: release
          if-no-files-found: error

  build-darwin-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Build
        run: |
          echo "darwin-arm64" > release
      - uses: actions/upload-artifact@v4
        with:
          name: release-darwin-arm64
          path: release
          if-no-files-found: error

  build-windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Build
        run: |
          "windows-x86_64" | Out-File -FilePath release
      - uses: actions/upload-artifact@v4
        with:
          name: release-windows-x86_64
          path: release
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux-x86_64
      - build-darwin-arm64
      - build-windows-x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
      - name: Output
        run: |
          mv release-linux-x86_64/release linux-x86_64
          mv release-darwin-arm64/release darwin-arm64
          mv release-windows-x86_64/release windows-x86_64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            linux-x86_64
            darwin-arm64
            windows-x86_64
